// Code generated by Slice Machine. DO NOT EDIT.

import ImageText from './ImageText';
import Text from './Text';

export {
	ImageText,
	Text,
};

export const components = {
	image_text: ImageText,
	text: Text,
};
