import Head from "next/head";

import Layout from "../components/layout";

import styles from "../styles/home.module.scss";

export default function Home() {
  return (
    <Layout>
      <div>
        <Head>
          <title>Next Prismic Starter</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main className={styles.main}>
          <h1 className={styles.title}>
            ✨ Bienvenue sur le Next Prismic Starter ✨
          </h1>
        </main>
      </div>
    </Layout>
  );
}
